version: "3"

services:
  postgres:
    image: "postgres"
    volumes:
      - postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust

  app:
    depends_on:
      - "postgres"
    build: .
    command: bash start.sh
    ports:
      - "3000:3000"
    volumes:
      - .:/CoinExchangeTrackerSample
      - gems:/gems
 

volumes:
  postgres:
  gems: